project:
  type: website
  output-dir: docs

website:
  title: "Notebook Collection"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - polarization_visuals.ipynb

format:
  html:
    auto-stretch: false
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

